#ifndef LV_CONF_H
#define LV_CONF_H

/* Application configuration, independent of the vendored LVGL source. */
#define LV_COLOR_DEPTH 16
#define LV_DPI_DEF 130
#define LV_USE_OS LV_OS_PTHREAD
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB
#define LV_USE_DRAW_SW 1
#define LV_DRAW_SW_DRAW_UNIT_CNT 1
#define LV_USE_LOG 1
#define LV_LOG_PRINTF 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_DEJAVU_16_PERSIAN_HEBREW 1
#define LV_FONT_DEFAULT &lv_font_montserrat_14

#define LV_USE_LIBPNG 1
#define LV_USE_FS_STDIO 1
#define LV_FS_STDIO_LETTER 'A'
#ifndef APP_ASSET_DIR
#define APP_ASSET_DIR "/usr/share/lvgl-com"
#endif
#define LV_FS_STDIO_PATH APP_ASSET_DIR
#define LV_FS_STDIO_CACHE_SIZE 0
#ifndef APP_USE_WAYLAND
#define APP_USE_WAYLAND 1
#endif
#define LV_USE_WAYLAND APP_USE_WAYLAND
#define LV_USE_LINUX_FBDEV (!APP_USE_WAYLAND)
#define LV_USE_EVDEV (!APP_USE_WAYLAND)
#define LV_USE_LINUX_DRM 0
#define LV_USE_OPENGLES 0
#define LV_LINUX_FBDEV_RENDER_MODE LV_DISPLAY_RENDER_MODE_PARTIAL
#define LV_LINUX_FBDEV_BUFFER_COUNT 2
#define LV_LINUX_FBDEV_BUFFER_SIZE 1080
#define LV_BUILD_EXAMPLES 0
#define LV_USE_THORVG_INTERNAL 0
#define LV_USE_THORVG_EXTERNAL 0
#define LV_USE_VECTOR_GRAPHIC 0
#define LV_USE_VG_LITE_THORVG 0
#define LV_USE_LOTTIE 0
#endif
